const CURRENCY_TYPES = {
    CURRENCY_CONVERT_REQUEST: '@currency/CURRENCY_CONVERT_REQUEST',
    CURRENCY_CONVERT_SUCCESS: '@currency/CURRENCY_CONVERT_SUCCESS',
    CURRENCY_CONVERT_FAILURE: '@currency/CURRENCY_CONVERT_FAILURE',
};

export default CURRENCY_TYPES;
